// Codegen for the dialog registry. Scans `*.dialog.tsx` files for
// `defineDialog({ schema: <expr> })` calls and emits a registry file that
// imports only zod plus the inline schemas — no dialog component code is
// referenced, so the registry stays tiny in the root bundle.

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import ts from "typescript";

export interface CodegenOptions {
	/** Absolute path to the directory to scan recursively for `*.dialog.tsx`. */
	scanDir: string;
	/** Absolute path of the generated registry file. */
	outPath: string;
	/**
	 * When `true`, parse failures throw. When `false`, they are collected as
	 * warnings and the offending file is skipped. Use `true` for build, `false`
	 * for dev so in-progress edits don't crash the dev server.
	 */
	strict: boolean;
}

export interface DialogEntry {
	dialogKey: string;
	filePath: string;
}

export interface CodegenResult {
	entries: DialogEntry[];
	changed: boolean;
	warnings: string[];
}

function findDialogFiles(dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		const s = statSync(full);
		if (s.isDirectory()) out.push(...findDialogFiles(full));
		else if (entry.endsWith(".dialog.tsx")) out.push(full);
	}
	return out;
}

interface ExtractedDialog {
	dialogKey: string;
	schemaText: string;
	filePath: string;
}

function extractDialogsFromFile(filePath: string, sf: ts.SourceFile): ExtractedDialog[] {
	const results: ExtractedDialog[] = [];

	const visit = (node: ts.Node) => {
		if (
			ts.isCallExpression(node) &&
			ts.isIdentifier(node.expression) &&
			node.expression.text === "defineDialog" &&
			node.arguments.length === 1 &&
			ts.isObjectLiteralExpression(node.arguments[0])
		) {
			const arg = node.arguments[0];
			const schemaProp = arg.properties.find(
				(p): p is ts.PropertyAssignment =>
					ts.isPropertyAssignment(p) && ts.isIdentifier(p.name) && p.name.text === "schema",
			);
			if (schemaProp) {
				const schemaExpr = schemaProp.initializer;
				const dialogKey = extractDialogKey(schemaExpr);
				if (!dialogKey) {
					throw new Error(
						`Could not extract dialogKey literal. Schemas must include ` +
							`\`dialogKey: z.literal("...")\` as a direct property.`,
					);
				}
				results.push({ dialogKey, schemaText: schemaExpr.getText(sf), filePath });
			}
		}
		ts.forEachChild(node, visit);
	};

	visit(sf);
	return results;
}

function extractDialogKey(node: ts.Node): string | null {
	let found: string | null = null;
	const visit = (n: ts.Node) => {
		if (found) return;
		if (
			ts.isPropertyAssignment(n) &&
			ts.isIdentifier(n.name) &&
			n.name.text === "dialogKey" &&
			ts.isCallExpression(n.initializer)
		) {
			const call = n.initializer;
			if (
				ts.isPropertyAccessExpression(call.expression) &&
				call.expression.name.text === "literal" &&
				call.arguments.length === 1 &&
				ts.isStringLiteral(call.arguments[0])
			) {
				found = call.arguments[0].text;
				return;
			}
		}
		ts.forEachChild(n, visit);
	};
	visit(node);
	return found;
}

/** Normalize any zod alias (e.g. `zod.object(...)`) to `z.object(...)`. */
function normalizeZodIdent(text: string): string {
	return text.replace(/\bzod\./g, "z.");
}

export function generateRegistry(opts: CodegenOptions): CodegenResult {
	const warnings: string[] = [];
	const extracted: ExtractedDialog[] = [];
	const files = findDialogFiles(opts.scanDir);

	for (const file of files) {
		try {
			const source = readFileSync(file, "utf8");
			const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
			extracted.push(...extractDialogsFromFile(file, sf));
		} catch (err) {
			const msg = `${file}: ${err instanceof Error ? err.message : String(err)}`;
			if (opts.strict) throw new Error(msg);
			warnings.push(`skipped (in-progress?) ${msg}`);
		}
	}

	const seen = new Map<string, string>();
	for (const e of extracted) {
		const prior = seen.get(e.dialogKey);
		if (prior) {
			// Duplicate keys are always fatal — they're data corruption, not in-progress edits.
			throw new Error(`Duplicate dialogKey "${e.dialogKey}":\n  - ${prior}\n  - ${e.filePath}`);
		}
		seen.set(e.dialogKey, e.filePath);
	}

	extracted.sort((a, b) => a.dialogKey.localeCompare(b.dialogKey));

	const header = `// AUTO-GENERATED by src/utils/dialogs/vite-plugin — do not edit.
// Imports zod ONLY. No dialog component files are referenced here, so
// importing this file does not pull form or tRPC code into consuming chunks.
${extracted.length > 0 ? '\nimport { z } from "zod";\n' : ""}`;

	const body = `
export const dialogSchemas = {
${extracted
	.map((e) => {
		const relPath = relative(dirname(opts.outPath), e.filePath);
		const normalized = normalizeZodIdent(e.schemaText);
		return `\t// from ${relPath}\n\t${JSON.stringify(e.dialogKey)}: ${normalized},`;
	})
	.join("\n")}
} as const;

export type DialogKey = keyof typeof dialogSchemas;
`;

	const next = header + body;
	const prev = existsSync(opts.outPath) ? readFileSync(opts.outPath, "utf8") : null;
	const changed = prev !== next;

	if (changed) {
		mkdirSync(dirname(opts.outPath), { recursive: true });
		writeFileSync(opts.outPath, next);
	}

	return {
		entries: extracted.map(({ dialogKey, filePath }) => ({ dialogKey, filePath })),
		changed,
		warnings,
	};
}
