// AUTO-GENERATED by src/utils/dialogs/vite-plugin — do not edit.
// Imports zod ONLY. No dialog component files are referenced here, so
// importing this file does not pull form or tRPC code into consuming chunks.

import { z } from "zod";

export const dialogSchemas = {
	// from components/board/share.dialog.tsx
	"project:share": z.object({
		dialogKey: z.literal("project:share"),
		dialogId: z.uuid(),
	}),
} as const;

export type DialogKey = keyof typeof dialogSchemas;
